export type LevelFilter = "" | "ERROR" | "WARN" | "INFO" | "DEBUG";
export type HealthStatus = "no-data" | "stable" | "monitor" | "degraded" | "critical";
export type TableDensity = "comfortable" | "compact";
export type ServiceFilter = string;

export type AnalyticsResponse = {
  error_counts_per_ip: Record<string, number>;
  log_level_distribution: Record<string, number>;
  service_volume: Record<string, number>;
  service_health: Record<string, HealthStatus>;
  top_failing_services: [string, number][];
  top_error_messages: [string, number][];
  service_error_share: Record<string, number>;
  error_timeline: Record<string, number>;
  record_timeline: Record<string, number>;
  total_errors: number;
  total_records: number;
  skipped_records: number;
  clean_record_ratio: number;
  unique_ip_count: number;
  impacted_service_count: number;
  error_free_service_count: number;
  source: string;
  applied_level: LevelFilter | null;
  applied_service: ServiceFilter | null;
  dominant_level: string | null;
  peak_error_window: string | null;
  noisiest_ip: string | null;
  busiest_service: string | null;
  first_seen_at: string | null;
  last_seen_at: string | null;
  observation_window_hours: number;
  health_status: HealthStatus;
  generated_at: string;
};
